### ISSUE TITLE
Gender neutral pronouns

### ISSUE THREAD

**Issue by jonathanKingston** [w3ctag/security-questionnaire#9]
I feel awfully pedantic raising this, however I feel completely gender neutral words is better than male and female (especially as the uses could be inferred to be negative connotations to that gender).

```
s/she/they/g
```

I'm aware this might remove some of the intended personal feel to the document but I saw it and thought it was worth the question.

Thanks

**Comment by mikewest** [comment]
I generally use female pronouns everywhere, intentionally. I know @tabatkins and others disagree with that practice, in favor of "they", as you've suggested here. I'm still thinking about whether I agree with the rationales Tab pointed me to.

If you want to submit a PR changing the pronouns to gender-neutral, I'd accept it.

**Comment by jonathanKingston** [comment]
I normally don't care about this so much (especially as there are positives to promote using she too); however I think perhaps more care should be used when the wording could be considered a negative connotation.

**Comment by tabatkins** [comment]
@jonathanKingston Use the `Repository` metadata to manually specify the repository; otherwise Bikeshed will automatically use the GH repo it finds itself in, which is your fork.

**Comment by tabatkins** [comment]
By the by, using gendered pronouns is still appropriate in a few places.  For example, using male and female when discussing a two-party transaction can make it clearer which party is being discussed at any given point.  Or when using the standard networking/crypto names (Alice, Bob, etc), using the appropriately-gendered pronoun is fine.

There's just no need to talk about gender at all otherwise.

**Comment by jonathanKingston** [comment]
:+1: very useful thank you both.
